const { Router } = require("express")
const { route } = require("../app")
const movieCtrl = require("../Controller/movieController")
const router = Router()

router.get("/peliculas", movieCtrl.getMovie)
router.get("/peliculas/actor", movieCtrl.getActor)
router.get("/peliculas/director", movieCtrl.getDirector)
router.get("/peliculas/guionista", movieCtrl.getWriter)
router.get("/peliculas/productora", movieCtrl.getProducer)
router.post("/peliculas", movieCtrl.postMovie)
router.post("/peliculas/actor", movieCtrl.addActor)
router.post("/peliculas/director", movieCtrl.addDirector)
router.post("/peliculas/guionista", movieCtrl.addWriter)
router.put("/peliculas", movieCtrl.updateMovie)
router.delete("/peliculas", movieCtrl.deleteMovie)
router.delete("/peliculas/actor", movieCtrl.deleteActor)
router.delete("/peliculas/director", movieCtrl.deleteDirector)
router.delete("/peliculas/guionista", movieCtrl.deleteWriter)
module.exports = router
